version: '3.9'

services:
  mariadb-galera-1: &cluster
    image: docker.io/bitnami/mariadb-galera:10.9.7
    networks:
      galera-network:
        ipv4_address: 172.20.0.10
    volumes:
      - mariadb_galera_data-1:/bitnami/mariadb
    environment: &env
      MARIADB_GALERA_CLUSTER_NAME: Galera Cluster
      MARIADB_EXTRA_FLAGS: --max-connect-errors=1000 --max_connections=500
      MARIADB_GALERA_MARIABACKUP_USER: backuper
      MARIADB_GALERA_MARIABACKUP_PASSWORD: backuper_password
      MARIADB_ROOT_PASSWORD: my_root_password
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: "yes"
      MARIADB_USER: ghost
      MARIADB_PASSWORD: ghost_password
      MARIADB_DATABASE: ghost_cms
      MARIADB_REPLICATION_USER: replication_user
      MARIADB_REPLICATION_PASSWORD: replication_passwor
      MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP: "yes"
      MARIADB_GALERA_CLUSTER_ADDRESS: "gcomm://mariadb-galera-1:4567,mariadb-galera-2:4567,mariadb-galera-3:4567"
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    restart: on-failure

  mariadb-galera-2:
    <<: *cluster
    environment:
       <<: *env
       MARIADB_GALERA_CLUSTER_BOOTSTRAP: "no"
    networks:
      galera-network:
        ipv4_address: 172.20.0.20
    volumes:
      - mariadb_galera_data-2:/bitnami/mariadb

  mariadb-galera-3:
    <<: *cluster
    environment:
       <<: *env
       MARIADB_GALERA_CLUSTER_BOOTSTRAP: "no"
    networks:
      galera-network:
        ipv4_address: 172.20.0.30
    volumes:
      - mariadb_galera_data-3:/bitnami/mariadb

#  mariadb-galera-4:
#    <<: *cluster
#    environment:
#       <<: *env
#       MARIADB_GALERA_CLUSTER_BOOTSTRAP: "no"
#    volumes:
#      - mariadb_galera_data-4:/bitnami/mariadb
#
#  mariadb-galera-5:
#    <<: *cluster
#    environment:
#       <<: *env
#       MARIADB_GALERA_CLUSTER_BOOTSTRAP: "no"
#    volumes:
#      - mariadb_galera_data-5:/bitnami/mariadb

  proxysql:
    image: percona/proxysql2:2.5.1
    networks:
      galera-network:
        ipv4_address: 172.20.0.50
      public:
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.proxysql.tls=true
        - traefik.http.routers.proxysql.rule=Host(`proxysql.roshamagin.site`)
        - traefik.http.routers.proxysql.entrypoints=websecure
        - traefik.http.routers.proxysql.tls.certresolver=myresolver
        - traefik.http.routers.proxysql.tls.passthrough=true
        - traefik.http.services.proxysql.loadbalancer.server.port=6080
        - traefik.http.services.proxysql.loadbalancer.server.scheme=https

  cron:
    image: schnitzler/mysqldump
    restart: always
    networks:
      galera-network:
    volumes:
      - ./bin/crontab:/var/spool/cron/crontabs/root
      - ./bin/backup:/usr/local/bin/backup
      - ./backup:/backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: mariadb-galera-1
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost_password
      MYSQL_DATABASE: ghost_cms

  backup:
    image: busybox
    networks:
      galera-network:
    volumes:
      - ./backup:/backup

volumes:
  mariadb_galera_data-1:
    driver: local
  mariadb_galera_data-2:
    driver: local
  mariadb_galera_data-3:
    driver: local

networks:
  galera-network:
    driver: overlay
    attachable: true
    ipam:
     config:
       - subnet: 172.20.0.0/16
  public:
    external: true